// Emits units.schema.json and the C# contract Core/UnitConfig.g.cs from units.schema.ts.
// `node build.mjs --check` fails when either committed output differs (no TypeBox↔C# drift).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { UnitsFile } from './units.schema.ts';
import { csharpValidation } from './invariants.mjs';

const here = dirname(fileURLToPath(import.meta.url));
export const schemaPath = join(here, 'units.schema.json');
export const csharpPath = join(here, '..', '..', 'RiskAI', 'Assets', 'RiskAI', 'Scripts', 'Core', 'UnitConfig.g.cs');
export const unitKindPath = join(here, '..', '..', 'RiskAI', 'Assets', 'RiskAI', 'Scripts', 'Core', 'UnitKind.g.cs');
export const validationPath = join(here, '..', '..', 'RiskAI', 'Assets', 'RiskAI', 'Scripts', 'Core', 'UnitConfigValidation.cs');
export const unitsPath = join(here, '..', '..', 'RiskAI', 'Assets', 'RiskAI', 'Resources', 'Config', 'units.json');

const FLAG_ENUMS = new Set(['WeaponTargetMask']);
const pascal = (name) => name[0].toUpperCase() + name.slice(1);
const isEnum = (s) => Array.isArray(s.anyOf) && s.anyOf.every((v) => typeof v.const === 'string');
const isNullableString = (s) => Array.isArray(s.anyOf) && s.anyOf.length === 2 &&
  s.anyOf.some((v) => v.type === 'string') && s.anyOf.some((v) => v.type === 'null');

// Named types appear once under $defs and are referenced elsewhere (JSON Schema forbids a repeated $id).
export function schemaDocument() {
  const defs = {};
  const lift = (node, root) => {
    if (Array.isArray(node)) return node.map((item) => lift(item, false));
    if (!node || typeof node !== 'object') return node;
    const copy = {};
    for (const [key, value] of Object.entries(node)) if (key !== '$id') copy[key] = lift(value, false);
    if (node.$id && !root) {
      if (!defs[node.$id]) defs[node.$id] = copy;
      return { $ref: `#/$defs/${node.$id}` };
    }
    return copy;
  };
  const body = lift(UnitsFile, true);
  return { $schema: 'https://json-schema.org/draft/2020-12/schema', $id: 'units.schema.json', ...body, $defs: defs };
}

export function schemaJson() {
  return JSON.stringify(schemaDocument(), null, 2) + '\n';
}

function collect(schema, types) {
  if (!schema || typeof schema !== 'object') return;
  if (schema.$id && !types.has(schema.$id)) types.set(schema.$id, schema);
  if (schema.properties) for (const value of Object.values(schema.properties)) collect(value, types);
  if (schema.items) collect(schema.items, types);
  if (schema.anyOf) for (const value of schema.anyOf) collect(value, types);
}

function csType(schema, optional) {
  if (schema.$id) return isEnum(schema) ? schema.$id + (optional ? '?' : '') : schema.$id;
  if (isNullableString(schema)) return 'string';
  if (schema.type === 'array') return csType(schema.items, false) + '[]';
  if (schema.const !== undefined && typeof schema.const === 'number') return 'int';
  const nullable = optional ? '?' : '';
  switch (schema.type) {
    case 'number': return 'float' + nullable;
    case 'integer': return 'int' + nullable;
    case 'boolean': return 'bool' + nullable;
    case 'string': return 'string';
    default: throw new Error('Unsupported schema node ' + JSON.stringify(schema));
  }
}

const doc = (text, indent) => text ? `${indent}/// <summary>${text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</summary>\n` : '';

export function csharp() {
  const types = new Map();
  collect(UnitsFile, types);
  let out = '// <auto-generated>\n// Generated by scripts/config/build.mjs from scripts/config/units.schema.ts. Do not edit.\n' +
    '// Regenerate: cd scripts/config && npm run build\n// </auto-generated>\nusing System;\n\nnamespace RiskAI.Core\n{\n';
  out += '    /// <summary>Schema facts the loader enforces: a required member must be present; Nullable admits an explicit null.</summary>\n' +
    '    [AttributeUsage(AttributeTargets.Field)]\n    public sealed class UnitConfigFieldAttribute : Attribute\n    {\n' +
    '        public bool Required;\n        public bool Nullable;\n    }\n\n';
  const enums = [...types.values()].filter(isEnum);
  const objects = [...types.values()].filter((s) => s.type === 'object');
  for (const schema of enums) {
    const flags = FLAG_ENUMS.has(schema.$id);
    out += doc(schema.description, '    ');
    if (flags) out += '    [Flags]\n';
    out += `    public enum ${schema.$id}\n    {\n`;
    if (flags) out += '        None = 0,\n';
    schema.anyOf.forEach((value, index) => {
      out += `        ${value.const}${flags ? ` = 1 << ${index}` : ''}${index + 1 < schema.anyOf.length ? ',' : ''}\n`;
    });
    out += '    }\n\n';
  }
  objects.forEach((schema, typeIndex) => {
    out += doc(schema.description, '    ');
    out += `    [Serializable]\n    public sealed class ${schema.$id}\n    {\n`;
    const required = new Set(schema.required ?? []);
    for (const [name, value] of Object.entries(schema.properties)) {
      const nullable = isNullableString(value);
      out += doc(value.description, '        ');
      if (required.has(name)) out += `        [UnitConfigField(Required = true${nullable ? ', Nullable = true' : ''})]\n`;
      out += `        public ${csType(value, !required.has(name))} ${pascal(name)};\n`;
    }
    out += '    }\n' + (typeIndex + 1 < objects.length ? '\n' : '');
  });
  return out + '}\n';
}

// The unit identity enum comes from units.json itself: one member per id, in file order.
// The ordinal is not an index anywhere; UnitCatalog maps every member to its type by id.
export function unitKindSource(units) {
  const ids = units.units.map((unit) => unit.id);
  let out = '// <auto-generated>\n// Generated by scripts/config/build.mjs from RiskAI/Assets/RiskAI/Resources/Config/units.json. Do not edit.\n' +
    '// Regenerate: cd scripts/config && npm run build\n// </auto-generated>\n\nnamespace RiskAI.Core\n{\n' +
    '    /// <summary>Unit type identity: one member per units.json id. Never persist or index by the ordinal.</summary>\n' +
    '    public enum UnitKind\n    {\n';
  ids.forEach((id, index) => { out += `        ${id}${index + 1 < ids.length ? ',' : ''}\n`; });
  return out + '    }\n}\n';
}

function emit(path, text, check) {
  const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === text) return true;
  if (check) { console.error(`out of date: ${path} (run npm run build)`); return false; }
  writeFileSync(path, text);
  console.log(`wrote ${path}`);
  return true;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  const units = JSON.parse(readFileSync(unitsPath, 'utf8'));
  const ok = [emit(schemaPath, schemaJson(), check), emit(csharpPath, csharp(), check),
    emit(unitKindPath, unitKindSource(units), check), emit(validationPath, csharpValidation(), check)].every(Boolean);
  if (check && ok) console.log('generated contract up to date');
  process.exit(ok ? 0 : 1);
}
