// <auto-generated>
// Generated by scripts/config/build.mjs from scripts/config/units.schema.ts. Do not edit.
// Regenerate: cd scripts/config && npm run build
// </auto-generated>
using System;

namespace RiskAI.Core
{
    /// <summary>Schema facts the loader enforces: a required member must be present; Nullable admits an explicit null.</summary>
    [AttributeUsage(AttributeTargets.Field)]
    public sealed class UnitConfigFieldAttribute : Attribute
    {
        public bool Required;
        public bool Nullable;
    }

    /// <summary>Where the unit moves: NavMesh land, SeaNavigation water, or fixed.</summary>
    public enum UnitDomain
    {
        Land,
        Sea,
        Static
    }

    /// <summary>Building that produces the unit. The grid cell is computed by ProductionHotkeys.</summary>
    public enum UnitBuilding
    {
        None,
        City,
        Harbor
    }

    /// <summary>Warcraft defense type.</summary>
    public enum ArmorKind
    {
        Unarmored,
        Light,
        Medium,
        Heavy,
        Fortified,
        Normal,
        Hero,
        Divine
    }

    /// <summary>Which clip plays for this weapon. Presentation reads this field; it does not list unit kinds.</summary>
    public enum WeaponSound
    {
        Blade,
        Lance,
        Bow,
        Firearm,
        Magic,
        Mortar,
        Cannon
    }

    /// <summary>Warcraft attack type (damage table row).</summary>
    public enum AttackKind
    {
        Normal,
        Piercing,
        Siege,
        Magic,
        Chaos,
        Hero,
        Spells
    }

    /// <summary>BodyEdges: 3D to the target approach point minus both body radii. CenterToApproach: 3D pivot to approach point. ToHull: XZ pivot to approach point (a ship hull). CenterToCenter: XZ pivot to pivot.</summary>
    public enum RangeMeasure
    {
        BodyEdges,
        CenterToApproach,
        ToHull,
        CenterToCenter
    }

    /// <summary>How a hit travels: instant, homing missile, artillery arc, missile with splash.</summary>
    public enum WeaponDelivery
    {
        Instant,
        Missile,
        Artillery,
        MissileSplash
    }

    /// <summary>Target follows the victim; LaunchPoint fixes the impact where it stood at release.</summary>
    public enum WeaponTargeting
    {
        Target,
        LaunchPoint
    }

    /// <summary>Target classes and relations; "Soldier" is the local class used by the Mage.</summary>
    [Flags]
    public enum WeaponTargetMask
    {
        None = 0,
        Air = 1 << 0,
        Debris = 1 << 1,
        Ground = 1 << 2,
        Item = 1 << 3,
        Structure = 1 << 4,
        Ward = 1 << 5,
        Self = 1 << 6,
        Tree = 1 << 7,
        Wall = 1 << 8,
        Enemy = 1 << 9,
        Neutral = 1 << 10,
        Ally = 1 << 11,
        Soldier = 1 << 12
    }

    /// <summary>Line of sight: terrain ray between aim points, or a NavMesh ray to the approach point.</summary>
    public enum UnitVisibility
    {
        TerrainRay,
        NavMeshRay
    }

    /// <summary>Equal scores: the lower entity id wins, or the first candidate found keeps it.</summary>
    public enum AcquisitionTieBreak
    {
        LowerEntityId,
        FirstFound
    }

    /// <summary>Where the art setup renders this portrait. Model claims the shared prefab (the Mortar cart is still a model portrait). Variant renders the unit view and does not claim a prefab.</summary>
    public enum PortraitSource
    {
        Model,
        Variant
    }

    /// <summary>Proxy shape for the strategic stand-in. Formation order uses the dense catalog index, never the kind ordinal.</summary>
    public enum UnitSilhouette
    {
        Infantry,
        Ranged,
        Mounted,
        Siege,
        Marine,
        Hull,
        Structure
    }

    /// <summary>units.json root.</summary>
    [Serializable]
    public sealed class UnitsFile
    {
        [UnitConfigField(Required = true)]
        public int Version;
        [UnitConfigField(Required = true)]
        public UnitConfig[] Units;
    }

    /// <summary>One unit type.</summary>
    [Serializable]
    public sealed class UnitConfig
    {
        /// <summary>Stable id; never derived from array order.</summary>
        [UnitConfigField(Required = true)]
        public string Id;
        /// <summary>Display text in both UI languages.</summary>
        [UnitConfigField(Required = true)]
        public UnitNames Names;
        /// <summary>Display text in both UI languages.</summary>
        public UnitNames Role;
        /// <summary>Provenance: raw Warcraft id, source profile and notes.</summary>
        [UnitConfigField(Required = true)]
        public UnitSource Source;
        /// <summary>Local deviations from the source.</summary>
        [UnitConfigField(Required = true)]
        public string[] Adaptation;
        /// <summary>Where the unit moves: NavMesh land, SeaNavigation water, or fixed.</summary>
        [UnitConfigField(Required = true)]
        public UnitDomain Domain;
        /// <summary>Gold cost.</summary>
        [UnitConfigField(Required = true)]
        public int Cost;
        /// <summary>Point value (bounty, reinforcement).</summary>
        [UnitConfigField(Required = true)]
        public int Points;
        /// <summary>Training time.</summary>
        [UnitConfigField(Required = true)]
        public float TrainSeconds;
        /// <summary>Required building level.</summary>
        [UnitConfigField(Required = true)]
        public int Level;
        /// <summary>Building that produces the unit. The grid cell is computed by ProductionHotkeys.</summary>
        [UnitConfigField(Required = true)]
        public UnitBuilding Building;
        /// <summary>Maximum health.</summary>
        [UnitConfigField(Required = true)]
        public float MaxHealth;
        /// <summary>Armor value.</summary>
        [UnitConfigField(Required = true)]
        public float Armor;
        /// <summary>Warcraft defense type.</summary>
        [UnitConfigField(Required = true)]
        public ArmorKind ArmorType;
        /// <summary>Mechanical: not healed by organic-only heals.</summary>
        [UnitConfigField(Required = true)]
        public bool Mechanical;
        /// <summary>False for capturable posts: attack their guardian.</summary>
        [UnitConfigField(Required = true)]
        public bool CanBeAttacked;
        /// <summary>Movement: base speed, forest drag on land, ship separation.</summary>
        [UnitConfigField(Required = true)]
        public UnitMovement Movement;
        /// <summary>A circle radius in metres.</summary>
        public UnitRadius Collision;
        /// <summary>A circle radius in metres.</summary>
        public UnitRadius Body;
        /// <summary>Oriented ship hull: builds the NavalArt model scale and the target BoxCollider.</summary>
        public UnitHull Hull;
        /// <summary>Square building footprint (towers).</summary>
        public UnitFootprint Footprint;
        /// <summary>Picking and presentation sizes, independent from collision.</summary>
        [UnitConfigField(Required = true)]
        public UnitVisual Visual;
        /// <summary>Spawn/unload spacing radius.</summary>
        public float? SpawnRadius;
        [UnitConfigField(Required = true)]
        public UnitWeapon[] Weapons;
        /// <summary>Tower weapon by host building.</summary>
        public UnitHostWeapons HostWeapons;
        /// <summary>Automatic target acquisition.</summary>
        public UnitAcquisition Acquisition;
        /// <summary>Typed capabilities; rules decide by these, never by type.</summary>
        [UnitConfigField(Required = true)]
        public UnitCapabilities Capabilities;
        /// <summary>Model, portrait, attack clip and proxy shape.</summary>
        [UnitConfigField(Required = true)]
        public UnitPresentation Presentation;
    }

    /// <summary>Display text in both UI languages.</summary>
    [Serializable]
    public sealed class UnitNames
    {
        [UnitConfigField(Required = true)]
        public string Es;
        [UnitConfigField(Required = true)]
        public string En;
    }

    /// <summary>Provenance: raw Warcraft id, source profile and notes.</summary>
    [Serializable]
    public sealed class UnitSource
    {
        [UnitConfigField(Required = true, Nullable = true)]
        public string Rawcode;
        public string Base;
        public string Notes;
    }

    /// <summary>Movement: base speed, forest drag on land, ship separation.</summary>
    [Serializable]
    public sealed class UnitMovement
    {
        /// <summary>Base speed in Unity metres per second (native / 50).</summary>
        [UnitConfigField(Required = true)]
        public float Speed;
        /// <summary>Forest canopies slow this unit (land only).</summary>
        [UnitConfigField(Required = true)]
        public bool ForestPenalty;
        /// <summary>Minimum distance kept from other units of the same domain (ships).</summary>
        public float? Separation;
    }

    /// <summary>A circle radius in metres.</summary>
    [Serializable]
    public sealed class UnitRadius
    {
        /// <summary>Radius in metres.</summary>
        [UnitConfigField(Required = true)]
        public float Radius;
    }

    /// <summary>Oriented ship hull: builds the NavalArt model scale and the target BoxCollider.</summary>
    [Serializable]
    public sealed class UnitHull
    {
        /// <summary>Collider length along the keel.</summary>
        [UnitConfigField(Required = true)]
        public float Length;
        /// <summary>Collider width.</summary>
        [UnitConfigField(Required = true)]
        public float Beam;
        /// <summary>Collider height.</summary>
        [UnitConfigField(Required = true)]
        public float Height;
        /// <summary>Collider centre height above the pivot.</summary>
        [UnitConfigField(Required = true)]
        public float CenterHeight;
        /// <summary>Model scale relative to the base silhouette.</summary>
        [UnitConfigField(Required = true)]
        public float Scale;
        /// <summary>Warship silhouette (false: transport silhouette).</summary>
        [UnitConfigField(Required = true)]
        public bool Warship;
        /// <summary>Draft the sea grid keeps around this hull. Every hull shares one value.</summary>
        [UnitConfigField(Required = true)]
        public float Clearance;
    }

    /// <summary>Square building footprint (towers).</summary>
    [Serializable]
    public sealed class UnitFootprint
    {
        /// <summary>Side length in metres.</summary>
        [UnitConfigField(Required = true)]
        public float Size;
    }

    /// <summary>Picking and presentation sizes, independent from collision.</summary>
    [Serializable]
    public sealed class UnitVisual
    {
        /// <summary>Picking/label height.</summary>
        [UnitConfigField(Required = true)]
        public float Height;
        /// <summary>Picking radius (half the standing width).</summary>
        [UnitConfigField(Required = true)]
        public float Radius;
        /// <summary>Rendered model height target; 0 keeps the model scale.</summary>
        [UnitConfigField(Required = true)]
        public float StandingHeight;
        /// <summary>Rendered model width target; 0 keeps the model scale.</summary>
        [UnitConfigField(Required = true)]
        public float StandingWidth;
        /// <summary>Source MDX Stand bounds (native / 50).</summary>
        public UnitStandingBounds Mdx;
    }

    /// <summary>Source MDX Stand bounds (native / 50).</summary>
    [Serializable]
    public sealed class UnitStandingBounds
    {
        /// <summary>Height.</summary>
        [UnitConfigField(Required = true)]
        public float Height;
        /// <summary>Width.</summary>
        [UnitConfigField(Required = true)]
        public float Width;
    }

    /// <summary>One attack: damage roll, timing, reach and delivery.</summary>
    [Serializable]
    public sealed class UnitWeapon
    {
        /// <summary>Weapon provenance id.</summary>
        [UnitConfigField(Required = true)]
        public string Source;
        /// <summary>Which clip plays for this weapon. Presentation reads this field; it does not list unit kinds.</summary>
        [UnitConfigField(Required = true)]
        public WeaponSound Sound;
        /// <summary>Warcraft attack type (damage table row).</summary>
        [UnitConfigField(Required = true)]
        public AttackKind AttackType;
        /// <summary>Base damage.</summary>
        [UnitConfigField(Required = true)]
        public float Base;
        /// <summary>Damage dice.</summary>
        [UnitConfigField(Required = true)]
        public int Dice;
        /// <summary>Sides per die.</summary>
        [UnitConfigField(Required = true)]
        public int Sides;
        /// <summary>Seconds between attacks.</summary>
        [UnitConfigField(Required = true)]
        public float Cooldown;
        /// <summary>Seconds from swing start to the hit/release.</summary>
        [UnitConfigField(Required = true)]
        public float AttackPoint;
        /// <summary>Recovery seconds after the hit (presentation).</summary>
        [UnitConfigField(Required = true)]
        public float Backswing;
        /// <summary>Weapon range in metres.</summary>
        [UnitConfigField(Required = true)]
        public float Range;
        /// <summary>Minimum range; closer targets make the unit back off.</summary>
        [UnitConfigField(Required = true)]
        public float MinRange;
        /// <summary>Ranged: terrain line of sight, rear formation rows, projectile/tracer delivery.</summary>
        [UnitConfigField(Required = true)]
        public bool Ranged;
        /// <summary>BodyEdges: 3D to the target approach point minus both body radii. CenterToApproach: 3D pivot to approach point. ToHull: XZ pivot to approach point (a ship hull). CenterToCenter: XZ pivot to pivot.</summary>
        [UnitConfigField(Required = true)]
        public RangeMeasure RangeMeasure;
        /// <summary>Melee hysteresis: first blow this far inside the reach; path this far inside it.</summary>
        public WeaponReach Reach;
        /// <summary>Extra distance allowed when a scheduled strike resolves.</summary>
        public float? StrikeTolerance;
        /// <summary>How a hit travels: instant, homing missile, artillery arc, missile with splash.</summary>
        [UnitConfigField(Required = true)]
        public WeaponDelivery Delivery;
        /// <summary>Target follows the victim; LaunchPoint fixes the impact where it stood at release.</summary>
        [UnitConfigField(Required = true)]
        public WeaponTargeting Targeting;
        /// <summary>Projectile speed (0 for instant).</summary>
        [UnitConfigField(Required = true)]
        public float ProjectileSpeed;
        /// <summary>Projectile flight time clamp in seconds; no max means unbounded.</summary>
        public WeaponFlightTime FlightTime;
        /// <summary>Area damage by rings and the classes/relations it may hit.</summary>
        public WeaponSplash Splash;
        [UnitConfigField(Required = true)]
        public WeaponTargetMask[] TargetMask;
        /// <summary>Draw an instant tracer for an instant ranged hit.</summary>
        [UnitConfigField(Required = true)]
        public bool Tracer;
    }

    /// <summary>Melee hysteresis: first blow this far inside the reach; path this far inside it.</summary>
    [Serializable]
    public sealed class WeaponReach
    {
        /// <summary>Path target inside the reach.</summary>
        [UnitConfigField(Required = true)]
        public float ApproachMargin;
        /// <summary>First blow inside the reach.</summary>
        [UnitConfigField(Required = true)]
        public float HoldMargin;
    }

    /// <summary>Projectile flight time clamp in seconds; no max means unbounded.</summary>
    [Serializable]
    public sealed class WeaponFlightTime
    {
        /// <summary>Minimum flight time.</summary>
        [UnitConfigField(Required = true)]
        public float Min;
        /// <summary>Maximum flight time.</summary>
        public float? Max;
    }

    /// <summary>Area damage by rings and the classes/relations it may hit.</summary>
    [Serializable]
    public sealed class WeaponSplash
    {
        [UnitConfigField(Required = true)]
        public SplashRing[] Rings;
        [UnitConfigField(Required = true)]
        public WeaponTargetMask[] Mask;
    }

    /// <summary>Area-damage ring: full damage inside the first, then each factor.</summary>
    [Serializable]
    public sealed class SplashRing
    {
        /// <summary>Outer radius of this ring.</summary>
        [UnitConfigField(Required = true)]
        public float Radius;
        /// <summary>Damage factor inside this ring.</summary>
        [UnitConfigField(Required = true)]
        public float Factor;
    }

    /// <summary>Tower weapon by host building.</summary>
    [Serializable]
    public sealed class UnitHostWeapons
    {
        /// <summary>One attack: damage roll, timing, reach and delivery.</summary>
        [UnitConfigField(Required = true)]
        public UnitWeapon Town;
        /// <summary>One attack: damage roll, timing, reach and delivery.</summary>
        [UnitConfigField(Required = true)]
        public UnitWeapon Harbor;
    }

    /// <summary>Automatic target acquisition.</summary>
    [Serializable]
    public sealed class UnitAcquisition
    {
        /// <summary>Automatic acquisition radius by the unit owner/order.</summary>
        [UnitConfigField(Required = true)]
        public AcquisitionRadius Radius;
        /// <summary>Maximum pursuit distance from the anchor for an autonomous target.</summary>
        public AcquisitionLeash Leash;
        /// <summary>Extra spatial query radius (long hulls).</summary>
        [UnitConfigField(Required = true)]
        public float QueryPadding;
        /// <summary>Score added per attacker already on a candidate (spreads melee).</summary>
        [UnitConfigField(Required = true)]
        public float PressureBias;
        /// <summary>Idle allies this close join against an attacker (0: none).</summary>
        [UnitConfigField(Required = true)]
        public float AllyAlertRadius;
        /// <summary>Turns on the attacker when hit while free.</summary>
        [UnitConfigField(Required = true)]
        public bool Retaliate;
        /// <summary>BodyEdges: 3D to the target approach point minus both body radii. CenterToApproach: 3D pivot to approach point. ToHull: XZ pivot to approach point (a ship hull). CenterToCenter: XZ pivot to pivot.</summary>
        [UnitConfigField(Required = true)]
        public RangeMeasure Measure;
        /// <summary>Line of sight: terrain ray between aim points, or a NavMesh ray to the approach point.</summary>
        [UnitConfigField(Required = true)]
        public UnitVisibility Visibility;
        /// <summary>Equal scores: the lower entity id wins, or the first candidate found keeps it.</summary>
        [UnitConfigField(Required = true)]
        public AcquisitionTieBreak TieBreak;
    }

    /// <summary>Automatic acquisition radius by the unit owner/order.</summary>
    [Serializable]
    public sealed class AcquisitionRadius
    {
        /// <summary>Player-owned unit.</summary>
        [UnitConfigField(Required = true)]
        public float Hostile;
        /// <summary>Neutral-owned unit.</summary>
        [UnitConfigField(Required = true)]
        public float Neutral;
        /// <summary>Unit holding position.</summary>
        [UnitConfigField(Required = true)]
        public float Hold;
    }

    /// <summary>Maximum pursuit distance from the anchor for an autonomous target.</summary>
    [Serializable]
    public sealed class AcquisitionLeash
    {
        /// <summary>Player-owned unit.</summary>
        [UnitConfigField(Required = true)]
        public float Hostile;
        /// <summary>Neutral-owned unit.</summary>
        [UnitConfigField(Required = true)]
        public float Neutral;
    }

    /// <summary>Typed capabilities; rules decide by these, never by type.</summary>
    [Serializable]
    public sealed class UnitCapabilities
    {
        /// <summary>Can claim a city/harbor circle.</summary>
        [UnitConfigField(Required = true)]
        public bool CanCapture;
        /// <summary>Can be bound as a city guardian.</summary>
        [UnitConfigField(Required = true)]
        public bool CanGarrison;
        /// <summary>Can board a transport.</summary>
        [UnitConfigField(Required = true)]
        public bool CanEmbark;
        /// <summary>Can be bound as a harbor guard ship.</summary>
        [UnitConfigField(Required = true)]
        public bool HarborGuard;
        /// <summary>Transport capability (A00V/Sch3).</summary>
        public UnitTransport Transport;
        /// <summary>Ahea autocast heal.</summary>
        public UnitHeal Heal;
        /// <summary>Aroa roar autocast.</summary>
        public UnitRoar Roar;
        /// <summary>Mana pool.</summary>
        public UnitMana Mana;
    }

    /// <summary>Transport capability (A00V/Sch3).</summary>
    [Serializable]
    public sealed class UnitTransport
    {
        /// <summary>Cargo slots.</summary>
        [UnitConfigField(Required = true)]
        public int Capacity;
        /// <summary>Boarding and unloading radius.</summary>
        [UnitConfigField(Required = true)]
        public float LoadRadius;
        /// <summary>Units selected per boarding order.</summary>
        [UnitConfigField(Required = true)]
        public int LoadLimit;
    }

    /// <summary>Ahea autocast heal.</summary>
    [Serializable]
    public sealed class UnitHeal
    {
        /// <summary>Health restored.</summary>
        [UnitConfigField(Required = true)]
        public float Amount;
        /// <summary>Heal range.</summary>
        [UnitConfigField(Required = true)]
        public float Range;
        /// <summary>Seconds between casts.</summary>
        [UnitConfigField(Required = true)]
        public float Cooldown;
        /// <summary>Mana per cast.</summary>
        [UnitConfigField(Required = true)]
        public float ManaCost;
        /// <summary>Seconds between searches while nobody needs healing (local).</summary>
        [UnitConfigField(Required = true)]
        public float Rescan;
        /// <summary>Maximum height difference to the target.</summary>
        [UnitConfigField(Required = true)]
        public float MaxVerticalDelta;
        /// <summary>Mechanical units are not healed.</summary>
        [UnitConfigField(Required = true)]
        public bool OrganicOnly;
    }

    /// <summary>Aroa roar autocast.</summary>
    [Serializable]
    public sealed class UnitRoar
    {
        /// <summary>Area radius.</summary>
        [UnitConfigField(Required = true)]
        public float Area;
        /// <summary>Buff duration.</summary>
        [UnitConfigField(Required = true)]
        public float Duration;
        /// <summary>Mana per cast.</summary>
        [UnitConfigField(Required = true)]
        public float ManaCost;
        /// <summary>Rolled damage bonus fraction.</summary>
        [UnitConfigField(Required = true)]
        public float DamageBonus;
        /// <summary>Seconds between autocast evaluations (local).</summary>
        [UnitConfigField(Required = true)]
        public float Evaluation;
    }

    /// <summary>Mana pool.</summary>
    [Serializable]
    public sealed class UnitMana
    {
        /// <summary>Maximum mana.</summary>
        [UnitConfigField(Required = true)]
        public float Max;
        /// <summary>Mana on spawn.</summary>
        [UnitConfigField(Required = true)]
        public float Initial;
        /// <summary>Mana per second.</summary>
        [UnitConfigField(Required = true)]
        public float Regen;
    }

    /// <summary>Model, portrait, attack clip and proxy shape.</summary>
    [Serializable]
    public sealed class UnitPresentation
    {
        /// <summary>Model prefab name.</summary>
        [UnitConfigField(Required = true, Nullable = true)]
        public string Model;
        /// <summary>Preferred portrait resource name.</summary>
        [UnitConfigField(Required = true)]
        public string Portrait;
        /// <summary>Portrait used until the preferred one is rendered.</summary>
        [UnitConfigField(Required = true)]
        public string PortraitFallback;
        /// <summary>Where the art setup renders this portrait. Model claims the shared prefab (the Mortar cart is still a model portrait). Variant renders the unit view and does not claim a prefab.</summary>
        [UnitConfigField(Required = true)]
        public PortraitSource PortraitSource;
        /// <summary>Attack clip; null for procedural attacks.</summary>
        [UnitConfigField(Required = true, Nullable = true)]
        public string AttackClip;
        /// <summary>Normalised clip time of the hit.</summary>
        [UnitConfigField(Required = true)]
        public float Contact;
        /// <summary>Proxy shape for the strategic stand-in. Formation order uses the dense catalog index, never the kind ordinal.</summary>
        [UnitConfigField(Required = true)]
        public UnitSilhouette Silhouette;
    }
}
