// <auto-generated>
// Generated by scripts/config/invariants.mjs. Do not edit.
// Regenerate: cd scripts/config && npm run build
// </auto-generated>
using System.Collections.Generic;

namespace RiskAI.Core
{
    /// <summary>Cross-field invariants of units.json, generated from scripts/config/invariants.mjs.</summary>
    public static class UnitConfigValidation
    {
        public static List<string> Errors(UnitsFile file)
        {
            var errors = new List<string>();
            if (file == null) { errors.Add("units.json is empty"); return errors; }
            if (file.Version != 1) errors.Add("units.json version " + file.Version + " is not supported");
            if ((!(file.Units != null) || (file.Units == null ? 0 : file.Units.Length) == 0)) errors.Add("units.json has no units");
            if (file.Units == null || file.Units.Length == 0) return errors;
            var seen = new HashSet<string>();
            float? clearance = null;
            foreach (var unit in file.Units)
            {
                if (unit == null) { errors.Add("null unit entry"); continue; }
                string at = "units[" + unit.Id + "]";
                if (!seen.Add(unit.Id)) errors.Add(at + ": duplicate id");
                if (((unit.Capabilities.Heal != null || unit.Capabilities.Roar != null) && !(unit.Capabilities.Mana != null))) errors.Add("" + at + ": heal/roar require mana");
                if ((unit.Capabilities.Transport != null && unit.Domain != UnitDomain.Sea)) errors.Add("" + at + ": transport is only for sea units");
                if ((unit.Domain == UnitDomain.Land && (!(unit.Collision != null) || !(unit.Body != null)))) errors.Add("" + at + ": land units need collision and body radii");
                if ((unit.Domain == UnitDomain.Sea && !(unit.Hull != null))) errors.Add("" + at + ": sea units need a hull");
                if ((unit.HostWeapons != null && unit.Domain != UnitDomain.Static)) errors.Add("" + at + ": hostWeapons are only for static posts");
                if ((unit.Acquisition != null && ((unit.Weapons == null ? 0 : unit.Weapons.Length) == 0 && !(unit.HostWeapons != null)))) errors.Add("" + at + ": acquisition without a weapon");
                if ((!(unit.Acquisition != null) && ((unit.Weapons == null ? 0 : unit.Weapons.Length) > 0 || unit.HostWeapons != null))) errors.Add("" + at + ": a weapon needs acquisition");
                if (unit.Domain == UnitDomain.Sea && unit.Hull != null)
                {
                    if (!(unit.Hull.Clearance > 0) || clearance != null && unit.Hull.Clearance != clearance) errors.Add("every sea hull shares one positive clearance (the sea grid is global)");
                    clearance = unit.Hull.Clearance;
                }
                if (unit.Weapons != null) foreach (var weapon in unit.Weapons) Check(unit, weapon, at, errors);
                if (unit.HostWeapons != null) { Check(unit, unit.HostWeapons.Town, at, errors); Check(unit, unit.HostWeapons.Harbor, at, errors); }
            }
            return errors;
        }

        static void Check(UnitConfig unit, UnitWeapon weapon, string at, List<string> errors)
        {
            if (weapon == null) return;
            string w = at + ".weapon[" + weapon.Source + "]";
            bool skipSplash = false;
                if ((weapon.RangeMeasure == RangeMeasure.BodyEdges && !(unit.Body != null))) errors.Add("" + w + ": BodyEdges needs body.radius");
                if ((weapon.RangeMeasure == RangeMeasure.BodyEdges && !(weapon.Reach != null))) errors.Add("" + w + ": BodyEdges needs reach margins");
                if ((weapon.Targeting == WeaponTargeting.LaunchPoint && weapon.Delivery != WeaponDelivery.Artillery)) errors.Add("" + w + ": LaunchPoint needs Artillery delivery");
                if ((weapon.Delivery == WeaponDelivery.Instant) != (weapon.ProjectileSpeed == 0)) errors.Add("" + w + ": projectileSpeed must be 0 exactly for Instant delivery");
                if (weapon.MinRange > weapon.Range) errors.Add("" + w + ": minRange above range");
                if ((weapon.FlightTime != null && (weapon.FlightTime.Max != null && weapon.FlightTime.Max < weapon.FlightTime.Min))) errors.Add("" + w + ": flightTime max below min");
                if ((weapon.Splash != null && (weapon.Splash.Rings == null ? 0 : weapon.Splash.Rings.Length) != 3)) { errors.Add("" + w + ": splash needs three rings"); skipSplash = true; }
                if (!skipSplash && (weapon.Splash != null && weapon.Splash.Rings[0].Factor != 1)) errors.Add("" + w + ": the first splash ring deals full damage");
                if (!skipSplash && (weapon.Splash != null && SplashShrinks(weapon.Splash.Rings))) errors.Add("" + w + ": splash rings must not shrink");
                if (!skipSplash && (weapon.Splash != null && weapon.Splash.Rings[weapon.Splash.Rings.Length - 1].Radius <= 0)) errors.Add("" + w + ": splash needs a positive outer radius");
        }

        static bool SplashShrinks(SplashRing[] rings)
        {
            if (rings == null) return false;
            for (int i = 1; i < rings.Length; i++) if (rings[i].Radius < rings[i - 1].Radius) return true;
            return false;
        }
    }
}
