// <auto-generated>
// Generated by scripts/config/build.mjs from RiskAI/Assets/RiskAI/Resources/Config/units.json. Do not edit.
// Regenerate: cd scripts/config && npm run build
// </auto-generated>

namespace RiskAI.Core
{
    /// <summary>Unit type identity: one member per units.json id. Never persist or index by the ordinal.</summary>
    public enum UnitKind
    {
        Footman,
        Archer,
        Knight,
        Mage,
        Mortar,
        Medic,
        MarinePrivate,
        MarineMajor,
        MarineGeneral,
        EliteRifleman,
        Roarer,
        ArmyGeneral,
        Artillery,
        Tank,
        Frigate,
        Transport,
        Warship,
        Battleship,
        ArmoredTransport,
        Tower
    }
}
